# Generated by Django 5.1 on 2024-08-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(blank=True, max_length=500, verbose_name='Départ')),
                ('arrival', models.CharField(blank=True, max_length=500, verbose_name='Arrivée')),
                ('date', models.DateField(verbose_name='Date')),
                ('hour', models.TimeField(verbose_name='Heure')),
                ('isReturn', models.BooleanField(default=False)),
            ],
        ),
    ]
