# Generated by Django 5.1 on 2024-08-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AeroportBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(blank=True, max_length=500, verbose_name='Départ')),
                ('date', models.DateField(verbose_name='Date')),
                ('hour', models.TimeField(verbose_name='Heure')),
                ('price', models.FloatField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DriverBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(blank=True, max_length=500, verbose_name='Départ')),
                ('arrival', models.CharField(blank=True, max_length=500, verbose_name='Arrivée')),
                ('date', models.DateField(verbose_name='Date')),
                ('hour', models.TimeField(verbose_name='Heure')),
                ('isReturn', models.BooleanField(default=False)),
                ('price', models.FloatField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PhotomatonBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('price', models.FloatField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TourismBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excursion', models.CharField(blank=True, max_length=500, verbose_name='Départ')),
                ('price', models.FloatField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UtilityBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date')),
                ('end_date', models.DateField(verbose_name='Date')),
                ('price', models.FloatField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WeddingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(blank=True, max_length=500, verbose_name='Arrivée')),
                ('date', models.DateField(verbose_name='Date')),
                ('hour', models.TimeField(verbose_name='Heure')),
                ('price', models.FloatField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
