# Generated by Django 5.1 on 2024-08-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aeroportbooking_driverbooking_photomatonbooking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeroportbooking',
            name='price',
            field=models.FloatField(default=False, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='driverbooking',
            name='price',
            field=models.FloatField(default=False, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='photomatonbooking',
            name='price',
            field=models.FloatField(default=False, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='tourismbooking',
            name='price',
            field=models.FloatField(default=False, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='utilitybooking',
            name='price',
            field=models.FloatField(default=False, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='weddingbooking',
            name='price',
            field=models.FloatField(default=False, verbose_name='Prix'),
        ),
    ]
