# Generated by Django 5.1 on 2024-10-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_aeroportbooking_customer_driverbooking_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeroportbooking',
            name='acti',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='acti',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='photomatonbooking',
            name='acti',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tourismbooking',
            name='acti',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='utilitybooking',
            name='acti',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='weddingbooking',
            name='acti',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
