# Generated by Django 5.1 on 2025-08-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverbooking',
            name='passengers',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, verbose_name='Nombre de passagers'),
        ),
    ]
