# Generated by Django 5.1 on 2025-08-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_driverbooking_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeroportbooking',
            name='bagages',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1, verbose_name='Nombre de bagages'),
        ),
        migrations.AddField(
            model_name='aeroportbooking',
            name='passengers',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, verbose_name='Nombre de passagers'),
        ),
    ]
