# Generated by Django 5.1 on 2025-08-21 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_aeroportbooking_bagages_aeroportbooking_passengers'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoboothBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service_type', models.CharField(choices=[('journee', 'À la journée'), ('heure', "À l'heure")], max_length=20)),
                ('hours', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2)])),
                ('days', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('transport', 'Transport'), ('aeroport', 'Aéroport')], max_length=20)),
                ('departure', models.CharField(max_length=200)),
                ('arrival', models.CharField(max_length=200)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('return_trip', models.BooleanField(default=False)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('passengers', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('luggage', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('service_type', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='driverbooking',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='photomatonbooking',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='tourismbooking',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='utilitybooking',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='weddingbooking',
            name='customer',
        ),
        migrations.DeleteModel(
            name='AeroportBooking',
        ),
        migrations.DeleteModel(
            name='DriverBooking',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PhotomatonBooking',
        ),
        migrations.DeleteModel(
            name='TourismBooking',
        ),
        migrations.DeleteModel(
            name='UtilityBooking',
        ),
        migrations.DeleteModel(
            name='WeddingBooking',
        ),
    ]
