# Generated by Django 4.0.2 on 2022-02-14 06:53

from django.db import migrations

def create_groups(apps, schema_migration):
    User = apps.get_model('authentication', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    
    administration = Group(name='administrator')
    administration.save()

    customer = Group(name='customer')
    customer.save()
    
    for user in User.objects.all():
        if user.role == 'ADMIN':
            administration.user_set.add(user)
        if user.role == 'CUSTOMER':
            customer.user_set.add(user)

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
