"""
Django settings for rgevents project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-121!52!zbw_*f%%=)$$sud$77(e0k#^v6g3hrelh2oi(slgk3-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',    
    'phonenumber_field',
    'authentication',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app.middleware.Custom404Middleware',  # Middleware personnalisé pour la page 404
]

ROOT_URLCONF = 'rgevents.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR.joinpath('templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rgevents.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

#STATIC_ROOT = BASE_DIR.joinpath('static/')

STATICFILES_DIRS = [
    BASE_DIR.joinpath('static')
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'authentication.User'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = LOGIN_URL

# Configuration pour le système de paiement
PAYMENT_SETTINGS = {
    'PAYPAL_CLIENT_ID': 'your_paypal_client_id_here',
    'PAYPAL_CLIENT_SECRET': 'your_paypal_client_secret_here',
    'PAYPAL_MODE': 'sandbox',  # 'sandbox' pour les tests, 'live' pour la production
    'CURRENCY': 'EUR',
    'SUCCESS_URL': '/payment/success/',
    'FAILURE_URL': '/payment/failed/',
}

# Configuration des emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # ou votre serveur SMTP
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'your_email@gmail.com'  # Votre email
EMAIL_HOST_PASSWORD = 'your_app_password'  # Mot de passe d'application
DEFAULT_FROM_EMAIL = 'RG Luxe Events <noreply@rgluxeevents.com>'

# Configuration pour l'envoi d'emails de confirmation
BOOKING_EMAILS = {
    'ADMIN_EMAIL': 'alexandre.boucher92@gmail.com',  # Email du responsable
    'COMPANY_NAME': 'RG Luxe Events',
    'COMPANY_WEBSITE': 'https://rgluxeevents.com',
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR.joinpath('media/')

# Configuration pour Google Maps API
GOOGLE_MAPS_API_KEY = 'AIzaSyCpYR4gr75AZB5wIVfS0d49G4-lTaSp4vY'  # Remplacez par votre vraie clé API

# Configuration pour l'autocomplétion des adresses
GOOGLE_MAPS_SETTINGS = {
    'DEFAULT_COUNTRY': 'RE',  # Code pays pour La Réunion
    'DEFAULT_LAT': -21.115141,  # Latitude du centre de La Réunion
    'DEFAULT_LNG': 55.536384,   # Longitude du centre de La Réunion
    'DEFAULT_ZOOM': 10,
}